-- ============================================================
-- TripSheetz: Visa requirements data from Travel Buddy API
-- Generated: 2026-02-20T18:23:15.034Z
-- Pairs: 95 successful, 0 failed
-- ============================================================

INSERT INTO visa_requirements (
  passport_code, destination_code, visa_status, visa_duration, visa_color,
  secondary_rule_name, secondary_rule_duration, secondary_rule_color, secondary_rule_link,
  passport_validity, mandatory_registration_name, mandatory_registration_color,
  mandatory_registration_link, embassy_url, last_verified
) VALUES
('US', 'JP', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, 'Valid on arrival', 'Customs declaration', 'yellow', 'https://link.travel-buddy.ai/?link=86E331T3', 'https://www.embassypages.com/usa#titlePlaceholder2', NOW()),
('US', 'TH', 'Visa not required', '60 days', 'green', NULL, NULL, NULL, NULL, '6 months', 'Arrival Card', 'yellow', 'https://link.travel-buddy.ai/?link=173E389T3', 'https://www.embassypages.com/usa#titlePlaceholder2', NOW()),
('US', 'FR', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, '3 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/usa#titlePlaceholder2', NOW()),
('US', 'IT', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, '3 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/usa#titlePlaceholder2', NOW()),
('US', 'KR', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, 'Valid on arrival', NULL, NULL, NULL, 'https://www.embassypages.com/usa#titlePlaceholder2', NOW()),
('US', 'AU', 'eTA', '90 days', 'yellow', NULL, NULL, NULL, NULL, 'Valid on arrival', NULL, NULL, NULL, 'https://www.embassypages.com/usa#titlePlaceholder2', NOW()),
('US', 'MX', 'Visa not required', '180 days', 'green', NULL, NULL, NULL, NULL, 'Valid on arrival', NULL, NULL, NULL, 'https://www.embassypages.com/usa#titlePlaceholder2', NOW()),
('US', 'DE', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, '3 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/usa#titlePlaceholder2', NOW()),
('US', 'SG', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, '6 months', 'Arrival Card', 'yellow', 'https://link.travel-buddy.ai/?link=158E380T3', 'https://www.embassypages.com/usa#titlePlaceholder2', NOW()),
('GB', 'JP', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, 'Valid on arrival', 'Customs declaration', 'yellow', 'https://link.travel-buddy.ai/?link=86E331T3', 'https://www.embassypages.com/uk#titlePlaceholder2', NOW()),
('GB', 'TH', 'Visa not required', '60 days', 'green', NULL, NULL, NULL, NULL, '6 months', 'Arrival Card', 'yellow', 'https://link.travel-buddy.ai/?link=173E389T3', 'https://www.embassypages.com/uk#titlePlaceholder2', NOW()),
('GB', 'FR', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, '3 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/uk#titlePlaceholder2', NOW()),
('GB', 'IT', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, '3 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/uk#titlePlaceholder2', NOW()),
('GB', 'US', 'ESTA', '90 days', 'yellow', NULL, NULL, NULL, NULL, '6 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/uk#titlePlaceholder2', NOW()),
('GB', 'KR', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, 'Valid on arrival', NULL, NULL, NULL, 'https://www.embassypages.com/uk#titlePlaceholder2', NOW()),
('GB', 'AU', 'eVisitors', '90 days', 'blue', NULL, NULL, NULL, NULL, 'Valid on arrival', NULL, NULL, NULL, 'https://www.embassypages.com/uk#titlePlaceholder2', NOW()),
('GB', 'MX', 'Visa not required', '180 days', 'green', NULL, NULL, NULL, NULL, 'Valid on arrival', NULL, NULL, NULL, 'https://www.embassypages.com/uk#titlePlaceholder2', NOW()),
('GB', 'DE', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, '3 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/uk#titlePlaceholder2', NOW()),
('GB', 'SG', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, '6 months', 'Arrival Card', 'yellow', 'https://link.travel-buddy.ai/?link=158E380T3', 'https://www.embassypages.com/uk#titlePlaceholder2', NOW()),
('CA', 'JP', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, 'Valid on arrival', 'Customs declaration', 'yellow', 'https://link.travel-buddy.ai/?link=86E331T3', 'https://www.embassypages.com/canada#titlePlaceholder2', NOW()),
('CA', 'TH', 'Visa not required', '60 days', 'green', NULL, NULL, NULL, NULL, '6 months', 'Arrival Card', 'yellow', 'https://link.travel-buddy.ai/?link=173E389T3', 'https://www.embassypages.com/canada#titlePlaceholder2', NOW()),
('CA', 'FR', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, '3 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/canada#titlePlaceholder2', NOW()),
('CA', 'IT', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, '3 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/canada#titlePlaceholder2', NOW()),
('CA', 'US', 'Visa not required', '180 days', 'green', NULL, NULL, NULL, NULL, '6 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/canada#titlePlaceholder2', NOW()),
('CA', 'KR', 'Visa not required', '180 days', 'green', NULL, NULL, NULL, NULL, 'Valid on arrival', NULL, NULL, NULL, 'https://www.embassypages.com/canada#titlePlaceholder2', NOW()),
('CA', 'AU', 'eTA', '90 days', 'yellow', NULL, NULL, NULL, NULL, 'Valid on arrival', NULL, NULL, NULL, 'https://www.embassypages.com/canada#titlePlaceholder2', NOW()),
('CA', 'MX', 'Visa not required', '180 days', 'green', NULL, NULL, NULL, NULL, 'Valid on arrival', NULL, NULL, NULL, 'https://www.embassypages.com/canada#titlePlaceholder2', NOW()),
('CA', 'DE', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, '3 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/canada#titlePlaceholder2', NOW()),
('CA', 'SG', 'Visa not required', '30 days', 'green', NULL, NULL, NULL, NULL, '6 months', 'Arrival Card', 'yellow', 'https://link.travel-buddy.ai/?link=158E380T3', 'https://www.embassypages.com/canada#titlePlaceholder2', NOW()),
('AU', 'JP', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, 'Valid on arrival', 'Customs declaration', 'yellow', 'https://link.travel-buddy.ai/?link=86E331T3', 'https://www.embassypages.com/australia#titlePlaceholder2', NOW()),
('AU', 'TH', 'Visa not required', '60 days', 'green', NULL, NULL, NULL, NULL, '6 months', 'Arrival Card', 'yellow', 'https://link.travel-buddy.ai/?link=173E389T3', 'https://www.embassypages.com/australia#titlePlaceholder2', NOW()),
('AU', 'FR', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, '3 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/australia#titlePlaceholder2', NOW()),
('AU', 'IT', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, '3 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/australia#titlePlaceholder2', NOW()),
('AU', 'US', 'ESTA', '90 days', 'yellow', NULL, NULL, NULL, NULL, '6 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/australia#titlePlaceholder2', NOW()),
('AU', 'KR', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, 'Valid on arrival', NULL, NULL, NULL, 'https://www.embassypages.com/australia#titlePlaceholder2', NOW()),
('AU', 'MX', 'Visa not required', '180 days', 'green', NULL, NULL, NULL, NULL, 'Valid on arrival', NULL, NULL, NULL, 'https://www.embassypages.com/australia#titlePlaceholder2', NOW()),
('AU', 'DE', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, '3 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/australia#titlePlaceholder2', NOW()),
('AU', 'SG', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, '6 months', 'Arrival Card', 'yellow', 'https://link.travel-buddy.ai/?link=158E380T3', 'https://www.embassypages.com/australia#titlePlaceholder2', NOW()),
('DE', 'JP', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, 'Valid on arrival', 'Customs declaration', 'yellow', 'https://link.travel-buddy.ai/?link=86E331T3', 'https://www.embassypages.com/germany#titlePlaceholder2', NOW()),
('DE', 'TH', 'Visa not required', '60 days', 'green', NULL, NULL, NULL, NULL, '6 months', 'Arrival Card', 'yellow', 'https://link.travel-buddy.ai/?link=173E389T3', 'https://www.embassypages.com/germany#titlePlaceholder2', NOW()),
('DE', 'FR', 'Freedom of movement', NULL, 'green', NULL, NULL, NULL, NULL, '3 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/germany#titlePlaceholder2', NOW()),
('DE', 'IT', 'Freedom of movement', NULL, 'green', NULL, NULL, NULL, NULL, '3 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/germany#titlePlaceholder2', NOW()),
('DE', 'US', 'ESTA', '90 days', 'yellow', NULL, NULL, NULL, NULL, '6 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/germany#titlePlaceholder2', NOW()),
('DE', 'KR', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, 'Valid on arrival', NULL, NULL, NULL, 'https://www.embassypages.com/germany#titlePlaceholder2', NOW()),
('DE', 'AU', 'eVisitors', '90 days', 'blue', NULL, NULL, NULL, NULL, 'Valid on arrival', NULL, NULL, NULL, 'https://www.embassypages.com/germany#titlePlaceholder2', NOW()),
('DE', 'MX', 'Visa not required', '180 days', 'green', NULL, NULL, NULL, NULL, 'Valid on arrival', NULL, NULL, NULL, 'https://www.embassypages.com/germany#titlePlaceholder2', NOW()),
('DE', 'SG', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, '6 months', 'Arrival Card', 'yellow', 'https://link.travel-buddy.ai/?link=158E380T3', 'https://www.embassypages.com/germany#titlePlaceholder2', NOW()),
('KR', 'JP', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, 'Valid on arrival', 'Customs declaration', 'yellow', 'https://link.travel-buddy.ai/?link=86E331T3', 'https://www.embassypages.com/korearepublic#titlePlaceholder2', NOW()),
('KR', 'TH', 'Visa not required', '60 days', 'green', NULL, NULL, NULL, NULL, '6 months', 'Arrival Card', 'yellow', 'https://link.travel-buddy.ai/?link=173E389T3', 'https://www.embassypages.com/korearepublic#titlePlaceholder2', NOW()),
('KR', 'FR', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, '3 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/korearepublic#titlePlaceholder2', NOW()),
('KR', 'IT', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, '3 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/korearepublic#titlePlaceholder2', NOW()),
('KR', 'US', 'ESTA', '90 days', 'yellow', NULL, NULL, NULL, NULL, '6 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/korearepublic#titlePlaceholder2', NOW()),
('KR', 'AU', 'eTA', '90 days', 'yellow', NULL, NULL, NULL, NULL, 'Valid on arrival', NULL, NULL, NULL, 'https://www.embassypages.com/korearepublic#titlePlaceholder2', NOW()),
('KR', 'MX', 'Visa not required', '180 days', 'green', NULL, NULL, NULL, NULL, 'Valid on arrival', NULL, NULL, NULL, 'https://www.embassypages.com/korearepublic#titlePlaceholder2', NOW()),
('KR', 'DE', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, '3 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/korearepublic#titlePlaceholder2', NOW()),
('KR', 'SG', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, '6 months', 'Arrival Card', 'yellow', 'https://link.travel-buddy.ai/?link=158E380T3', 'https://www.embassypages.com/korearepublic#titlePlaceholder2', NOW()),
('CN', 'JP', 'eVisa', '90 days', 'blue', NULL, NULL, NULL, NULL, 'Valid on arrival', 'Customs declaration', 'yellow', 'https://link.travel-buddy.ai/?link=86E331T3', 'https://www.embassypages.com/china#titlePlaceholder2', NOW()),
('CN', 'TH', 'Visa not required', '60 days', 'green', NULL, NULL, NULL, NULL, '6 months', 'Arrival Card', 'yellow', 'https://link.travel-buddy.ai/?link=173E389T3', 'https://www.embassypages.com/china#titlePlaceholder2', NOW()),
('CN', 'FR', 'Visa required', NULL, 'red', NULL, NULL, NULL, NULL, '3 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/china#titlePlaceholder2', NOW()),
('CN', 'IT', 'Visa required', NULL, 'red', NULL, NULL, NULL, NULL, '3 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/china#titlePlaceholder2', NOW()),
('CN', 'US', 'Visa required', NULL, 'red', NULL, NULL, NULL, NULL, '6 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/china#titlePlaceholder2', NOW()),
('CN', 'KR', 'Online visa required', NULL, 'red', NULL, NULL, NULL, NULL, 'Valid on arrival', 'e-Arrival', 'yellow', 'https://link.travel-buddy.ai/?link=94E422T3', 'https://www.embassypages.com/china#titlePlaceholder2', NOW()),
('CN', 'AU', 'Online visa required', NULL, 'red', NULL, NULL, NULL, NULL, 'Valid on arrival', NULL, NULL, NULL, 'https://www.embassypages.com/china#titlePlaceholder2', NOW()),
('CN', 'MX', 'Visa required', NULL, 'red', NULL, NULL, NULL, NULL, 'Valid on arrival', NULL, NULL, NULL, 'https://www.embassypages.com/china#titlePlaceholder2', NOW()),
('CN', 'DE', 'Visa required', NULL, 'red', NULL, NULL, NULL, NULL, '3 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/china#titlePlaceholder2', NOW()),
('CN', 'SG', 'Visa not required', '30 days', 'green', NULL, NULL, NULL, NULL, '6 months', 'Arrival Card', 'yellow', 'https://link.travel-buddy.ai/?link=158E380T3', 'https://www.embassypages.com/china#titlePlaceholder2', NOW()),
('IN', 'JP', 'eVisa', '90 days', 'blue', NULL, NULL, NULL, NULL, 'Valid on arrival', 'Customs declaration', 'yellow', 'https://link.travel-buddy.ai/?link=86E331T3', 'https://www.embassypages.com/india#titlePlaceholder2', NOW()),
('IN', 'TH', 'Visa not required', '60 days', 'green', NULL, NULL, NULL, NULL, '6 months', 'Arrival Card', 'yellow', 'https://link.travel-buddy.ai/?link=173E389T3', 'https://www.embassypages.com/india#titlePlaceholder2', NOW()),
('IN', 'FR', 'Visa required', NULL, 'red', NULL, NULL, NULL, NULL, '3 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/india#titlePlaceholder2', NOW()),
('IN', 'IT', 'Visa required', NULL, 'red', NULL, NULL, NULL, NULL, '3 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/india#titlePlaceholder2', NOW()),
('IN', 'US', 'Visa required', NULL, 'red', NULL, NULL, NULL, NULL, '6 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/india#titlePlaceholder2', NOW()),
('IN', 'KR', 'Online visa required', NULL, 'red', NULL, NULL, NULL, NULL, 'Valid on arrival', 'e-Arrival', 'yellow', 'https://link.travel-buddy.ai/?link=94E422T3', 'https://www.embassypages.com/india#titlePlaceholder2', NOW()),
('IN', 'AU', 'Online visa required', NULL, 'red', NULL, NULL, NULL, NULL, 'Valid on arrival', NULL, NULL, NULL, 'https://www.embassypages.com/india#titlePlaceholder2', NOW()),
('IN', 'MX', 'Visa required', NULL, 'red', NULL, NULL, NULL, NULL, 'Valid on arrival', NULL, NULL, NULL, 'https://www.embassypages.com/india#titlePlaceholder2', NOW()),
('IN', 'DE', 'Visa required', NULL, 'red', NULL, NULL, NULL, NULL, '3 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/india#titlePlaceholder2', NOW()),
('IN', 'SG', 'eVisa', NULL, 'blue', NULL, NULL, NULL, NULL, '6 months', 'Arrival Card', 'yellow', 'https://link.travel-buddy.ai/?link=158E380T3', 'https://www.embassypages.com/india#titlePlaceholder2', NOW()),
('JP', 'TH', 'Visa not required', '60 days', 'green', NULL, NULL, NULL, NULL, '6 months', 'Arrival Card', 'yellow', 'https://link.travel-buddy.ai/?link=173E389T3', 'https://www.embassypages.com/japan#titlePlaceholder2', NOW()),
('JP', 'FR', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, '3 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/japan#titlePlaceholder2', NOW()),
('JP', 'IT', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, '3 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/japan#titlePlaceholder2', NOW()),
('JP', 'US', 'ESTA', '90 days', 'yellow', NULL, NULL, NULL, NULL, '6 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/japan#titlePlaceholder2', NOW()),
('JP', 'KR', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, 'Valid on arrival', NULL, NULL, NULL, 'https://www.embassypages.com/japan#titlePlaceholder2', NOW()),
('JP', 'AU', 'eTA', '90 days', 'yellow', NULL, NULL, NULL, NULL, 'Valid on arrival', NULL, NULL, NULL, 'https://www.embassypages.com/japan#titlePlaceholder2', NOW()),
('JP', 'MX', 'Visa not required', '180 days', 'green', NULL, NULL, NULL, NULL, 'Valid on arrival', NULL, NULL, NULL, 'https://www.embassypages.com/japan#titlePlaceholder2', NOW()),
('JP', 'DE', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, '3 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/japan#titlePlaceholder2', NOW()),
('JP', 'SG', 'Visa not required', '30 days', 'green', NULL, NULL, NULL, NULL, '6 months', 'Arrival Card', 'yellow', 'https://link.travel-buddy.ai/?link=158E380T3', 'https://www.embassypages.com/japan#titlePlaceholder2', NOW()),
('BR', 'JP', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, 'Valid on arrival', 'Customs declaration', 'yellow', 'https://link.travel-buddy.ai/?link=86E331T3', 'https://www.embassypages.com/brazil#titlePlaceholder2', NOW()),
('BR', 'TH', 'Visa not required', '60 days', 'green', NULL, NULL, NULL, NULL, '6 months', 'Arrival Card', 'yellow', 'https://link.travel-buddy.ai/?link=173E389T3', 'https://www.embassypages.com/brazil#titlePlaceholder2', NOW()),
('BR', 'FR', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, '3 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/brazil#titlePlaceholder2', NOW()),
('BR', 'IT', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, '3 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/brazil#titlePlaceholder2', NOW()),
('BR', 'US', 'Visa required', NULL, 'red', NULL, NULL, NULL, NULL, '6 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/brazil#titlePlaceholder2', NOW()),
('BR', 'KR', 'eTA', '90 days', 'yellow', NULL, NULL, NULL, NULL, 'Valid on arrival', NULL, NULL, NULL, 'https://www.embassypages.com/brazil#titlePlaceholder2', NOW()),
('BR', 'AU', 'Online visa required', NULL, 'red', NULL, NULL, NULL, NULL, 'Valid on arrival', NULL, NULL, NULL, 'https://www.embassypages.com/brazil#titlePlaceholder2', NOW()),
('BR', 'MX', 'eTA', '180 days', 'yellow', NULL, NULL, NULL, NULL, 'Valid on arrival', NULL, NULL, NULL, 'https://www.embassypages.com/brazil#titlePlaceholder2', NOW()),
('BR', 'DE', 'Visa not required', '90 days', 'green', NULL, NULL, NULL, NULL, '3 months longer than the duration of stay', NULL, NULL, NULL, 'https://www.embassypages.com/brazil#titlePlaceholder2', NOW()),
('BR', 'SG', 'Visa not required', '30 days', 'green', NULL, NULL, NULL, NULL, '6 months', 'Arrival Card', 'yellow', 'https://link.travel-buddy.ai/?link=158E380T3', 'https://www.embassypages.com/brazil#titlePlaceholder2', NOW());
